modLoader="javafml"
loaderVersion="[28,]"
logoFile="logo.png"
authors="Farcr, Musicano, and Pugz"
credits=""

[[mods]]
    modId="swampexpansion"
    version="1.0.0"
    displayName="Swamp Expansion"
    credits="Farcr, Musicano, and Pugz"
    description='''
    Expanding the Swamps. New wood, new blocks, new friends.
    '''

[[dependencies.bloomful]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"